from enum import Enum


class ErrorCode(str, Enum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    NAV_CACHE_MISSING = "NAV_CACHE_MISSING"
    FUND_UNIVERSE_CACHE_MISSING = "FUND_UNIVERSE_CACHE_MISSING"
    INSUFFICIENT_NAV_HISTORY = "INSUFFICIENT_NAV_HISTORY"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    SIMULATION_FAILED = "SIMULATION_FAILED"
